/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Authentification (void);
GtkWidget* create_Acceuil (void);
GtkWidget* create_espace_admin (void);
GtkWidget* create_Ajout_agent (void);
GtkWidget* create_Affich_agent (void);
GtkWidget* create_Inscription_client (void);
GtkWidget* create_gestion_client (void);
GtkWidget* create_modifier_c (void);
GtkWidget* create_erreur (void);
