/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espace_client (void)
{
  GtkWidget *espace_client;
  GtkWidget *fixed1;
  GtkWidget *se_deconnecter;
  GtkWidget *profil;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label22;
  GtkWidget *actualiser;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label81;
  GtkWidget *label82;
  GtkWidget *notebook1;
  GtkWidget *fixed9;
  GtkWidget *rechercher_vols_entry;
  GtkWidget *treeview_vols_client;
  GtkWidget *vols_button;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label26;
  GtkWidget *Vols;
  GtkWidget *fixed7;
  GtkWidget *treeview_hotels_client;
  GtkWidget *rechercher_hotel_entry;
  GtkWidget *hotels_button;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label21;
  GtkWidget *hist_payer_hotels;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label104;
  GtkWidget *Hotels;
  GtkWidget *fixed4;
  GtkWidget *treeview_location_voiture_client;
  GtkWidget *rechercher_voiture_entry;
  GtkWidget *voitures_button;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label28;
  GtkWidget *Location_voitures;
  GtkWidget *fixed5;
  GtkWidget *treeview_sejours_client;
  GtkWidget *rechercher_sejours_entry;
  GtkWidget *sejours_button;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label27;
  GtkWidget *Sejours;
  GtkWidget *fixed6;
  GtkWidget *treeview_reclamation_client;
  GtkWidget *entry_cin_reclamation;
  GtkWidget *ajouter_reclamation;
  GtkWidget *supprimer_reclamation;
  GtkWidget *entry_nom_reclamation;
  GtkWidget *entry_prenom_reclamation;
  GtkWidget *entry_date_reclamation;
  GtkWidget *entry_mes_reclamation;
  GtkWidget *modifier_reclamation;
  GtkWidget *Reclamation;

  espace_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (espace_client, 928, 520);
  gtk_window_set_title (GTK_WINDOW (espace_client), _("espac_client"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (espace_client), fixed1);

  se_deconnecter = gtk_button_new_with_mnemonic (_("Se d\303\251connecter"));
  gtk_widget_show (se_deconnecter);
  gtk_fixed_put (GTK_FIXED (fixed1), se_deconnecter, 775, 20);
  gtk_widget_set_size_request (se_deconnecter, 150, 40);
  gtk_container_set_border_width (GTK_CONTAINER (se_deconnecter), 1);

  profil = gtk_button_new ();
  gtk_widget_show (profil);
  gtk_fixed_put (GTK_FIXED (fixed1), profil, 620, 20);
  gtk_widget_set_size_request (profil, 150, 40);
  gtk_container_set_border_width (GTK_CONTAINER (profil), 2);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (profil), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-orientation-landscape", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Mon profil"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox6), label22, FALSE, FALSE, 0);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed1), actualiser, 465, 20);
  gtk_widget_set_size_request (actualiser, 150, 40);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (actualiser), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label81 = gtk_label_new_with_mnemonic (_("actualiser"));
  gtk_widget_show (label81);
  gtk_box_pack_start (GTK_BOX (hbox11), label81, FALSE, FALSE, 0);

  label82 = gtk_label_new (_("<b><i><span foreground=\"darkcyan\" size=\"xx-large\">Sky Travel</span></i></b>"));
  gtk_widget_show (label82);
  gtk_fixed_put (GTK_FIXED (fixed1), label82, 0, 0);
  gtk_widget_set_size_request (label82, 354, 83);
  gtk_label_set_use_markup (GTK_LABEL (label82), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 40, 96);
  gtk_widget_set_size_request (notebook1, 848, 424);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  rechercher_vols_entry = gtk_entry_new ();
  gtk_widget_show (rechercher_vols_entry);
  gtk_fixed_put (GTK_FIXED (fixed9), rechercher_vols_entry, 112, 8);
  gtk_widget_set_size_request (rechercher_vols_entry, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rechercher_vols_entry), 8226);

  treeview_vols_client = gtk_tree_view_new ();
  gtk_widget_show (treeview_vols_client);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview_vols_client, 10, 50);
  gtk_widget_set_size_request (treeview_vols_client, 824, 255);

  vols_button = gtk_button_new ();
  gtk_widget_show (vols_button);
  gtk_fixed_put (GTK_FIXED (fixed9), vols_button, 368, 8);
  gtk_widget_set_size_request (vols_button, 128, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (vols_button), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox7), label26, FALSE, FALSE, 0);

  Vols = gtk_label_new (_("Vols"));
  gtk_widget_show (Vols);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), Vols);
  gtk_widget_set_size_request (Vols, 120, 60);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);
  gtk_widget_set_size_request (fixed7, 824, 296);

  treeview_hotels_client = gtk_tree_view_new ();
  gtk_widget_show (treeview_hotels_client);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview_hotels_client, 10, 50);
  gtk_widget_set_size_request (treeview_hotels_client, 824, 255);

  rechercher_hotel_entry = gtk_entry_new ();
  gtk_widget_show (rechercher_hotel_entry);
  gtk_fixed_put (GTK_FIXED (fixed7), rechercher_hotel_entry, 112, 8);
  gtk_widget_set_size_request (rechercher_hotel_entry, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rechercher_hotel_entry), 8226);

  hotels_button = gtk_button_new ();
  gtk_widget_show (hotels_button);
  gtk_fixed_put (GTK_FIXED (fixed7), hotels_button, 368, 8);
  gtk_widget_set_size_request (hotels_button, 128, 29);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (hotels_button), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox5), label21, FALSE, FALSE, 0);

  hist_payer_hotels = gtk_button_new ();
  gtk_widget_show (hist_payer_hotels);
  gtk_fixed_put (GTK_FIXED (fixed7), hist_payer_hotels, 681, 312);
  gtk_widget_set_size_request (hist_payer_hotels, 111, 40);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (hist_payer_hotels), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("historique"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox16), label104, FALSE, FALSE, 0);

  Hotels = gtk_label_new (_("Hotels"));
  gtk_widget_show (Hotels);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), Hotels);
  gtk_widget_set_size_request (Hotels, 120, 60);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview_location_voiture_client = gtk_tree_view_new ();
  gtk_widget_show (treeview_location_voiture_client);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview_location_voiture_client, 10, 50);
  gtk_widget_set_size_request (treeview_location_voiture_client, 824, 255);

  rechercher_voiture_entry = gtk_entry_new ();
  gtk_widget_show (rechercher_voiture_entry);
  gtk_fixed_put (GTK_FIXED (fixed4), rechercher_voiture_entry, 112, 8);
  gtk_widget_set_size_request (rechercher_voiture_entry, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rechercher_voiture_entry), 8226);

  voitures_button = gtk_button_new ();
  gtk_widget_show (voitures_button);
  gtk_fixed_put (GTK_FIXED (fixed4), voitures_button, 368, 8);
  gtk_widget_set_size_request (voitures_button, 128, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (voitures_button), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox9), label28, FALSE, FALSE, 0);

  Location_voitures = gtk_label_new (_("Location voitures"));
  gtk_widget_show (Location_voitures);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), Location_voitures);
  gtk_widget_set_size_request (Location_voitures, 120, 60);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  treeview_sejours_client = gtk_tree_view_new ();
  gtk_widget_show (treeview_sejours_client);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview_sejours_client, 10, 50);
  gtk_widget_set_size_request (treeview_sejours_client, 824, 255);

  rechercher_sejours_entry = gtk_entry_new ();
  gtk_widget_show (rechercher_sejours_entry);
  gtk_fixed_put (GTK_FIXED (fixed5), rechercher_sejours_entry, 112, 8);
  gtk_widget_set_size_request (rechercher_sejours_entry, 224, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rechercher_sejours_entry), 8226);

  sejours_button = gtk_button_new ();
  gtk_widget_show (sejours_button);
  gtk_fixed_put (GTK_FIXED (fixed5), sejours_button, 368, 8);
  gtk_widget_set_size_request (sejours_button, 128, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (sejours_button), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox8), label27, FALSE, FALSE, 0);

  Sejours = gtk_label_new (_("Sejours"));
  gtk_widget_show (Sejours);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), Sejours);
  gtk_widget_set_size_request (Sejours, 120, 60);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed6);

  treeview_reclamation_client = gtk_tree_view_new ();
  gtk_widget_show (treeview_reclamation_client);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview_reclamation_client, 24, 32);
  gtk_widget_set_size_request (treeview_reclamation_client, 752, 264);

  entry_cin_reclamation = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed6), entry_cin_reclamation, 800, 88);
  gtk_widget_set_size_request (entry_cin_reclamation, 28, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_cin_reclamation), 8226);

  ajouter_reclamation = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (ajouter_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), ajouter_reclamation, 516, 309);
  gtk_widget_set_size_request (ajouter_reclamation, 98, 40);

  supprimer_reclamation = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (supprimer_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), supprimer_reclamation, 637, 309);
  gtk_widget_set_size_request (supprimer_reclamation, 92, 40);

  entry_nom_reclamation = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed6), entry_nom_reclamation, 800, 40);
  gtk_widget_set_size_request (entry_nom_reclamation, 28, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_reclamation), 8226);

  entry_prenom_reclamation = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed6), entry_prenom_reclamation, 800, 128);
  gtk_widget_set_size_request (entry_prenom_reclamation, 28, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom_reclamation), 8226);

  entry_date_reclamation = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed6), entry_date_reclamation, 800, 184);
  gtk_widget_set_size_request (entry_date_reclamation, 28, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_date_reclamation), 8226);

  entry_mes_reclamation = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed6), entry_mes_reclamation, 808, 232);
  gtk_widget_set_size_request (entry_mes_reclamation, 28, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mes_reclamation), 8226);

  modifier_reclamation = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed6), modifier_reclamation, 752, 307);
  gtk_widget_set_size_request (modifier_reclamation, 87, 40);

  Reclamation = gtk_label_new (_("Reclamation"));
  gtk_widget_show (Reclamation);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), Reclamation);
  gtk_widget_set_size_request (Reclamation, 120, 60);

  g_signal_connect ((gpointer) se_deconnecter, "clicked",
                    G_CALLBACK (on_se_deconnecter_clicked),
                    NULL);
  g_signal_connect ((gpointer) profil, "clicked",
                    G_CALLBACK (on_profil_clicked),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_vols_client, "row_activated",
                    G_CALLBACK (on_treeview_vols_client_row_activated),
                    NULL);
  g_signal_connect ((gpointer) vols_button, "clicked",
                    G_CALLBACK (on_vols_button_enter),
                    NULL);
  g_signal_connect ((gpointer) treeview_hotels_client, "row_activated",
                    G_CALLBACK (on_treeview_hotels_client_row_activated),
                    NULL);
  g_signal_connect ((gpointer) hotels_button, "clicked",
                    G_CALLBACK (on_hotels_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) hist_payer_hotels, "clicked",
                    G_CALLBACK (on_hist_payer_hotels_clicked),
                    NULL);
  g_signal_connect ((gpointer) Hotels, "activate_link",
                    G_CALLBACK (on_Hotels_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) treeview_location_voiture_client, "row_activated",
                    G_CALLBACK (on_treeview_location_voiture_client_row_activated),
                    NULL);
  g_signal_connect ((gpointer) voitures_button, "clicked",
                    G_CALLBACK (on_voitures_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_sejours_client, "row_activated",
                    G_CALLBACK (on_treeview_sejours_client_row_activated),
                    NULL);
  g_signal_connect ((gpointer) sejours_button, "clicked",
                    G_CALLBACK (on_sejours_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_reclamation_client, "row_activated",
                    G_CALLBACK (on_treeview_reclamation_client_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ajouter_reclamation, "clicked",
                    G_CALLBACK (on_ajouter_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_reclamation, "clicked",
                    G_CALLBACK (on_supprimer_reclamation_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_reclamation, "clicked",
                    G_CALLBACK (on_modifier_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_client, espace_client, "espace_client");
  GLADE_HOOKUP_OBJECT (espace_client, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (espace_client, se_deconnecter, "se_deconnecter");
  GLADE_HOOKUP_OBJECT (espace_client, profil, "profil");
  GLADE_HOOKUP_OBJECT (espace_client, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (espace_client, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (espace_client, image6, "image6");
  GLADE_HOOKUP_OBJECT (espace_client, label22, "label22");
  GLADE_HOOKUP_OBJECT (espace_client, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (espace_client, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (espace_client, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (espace_client, image11, "image11");
  GLADE_HOOKUP_OBJECT (espace_client, label81, "label81");
  GLADE_HOOKUP_OBJECT (espace_client, label82, "label82");
  GLADE_HOOKUP_OBJECT (espace_client, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (espace_client, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (espace_client, rechercher_vols_entry, "rechercher_vols_entry");
  GLADE_HOOKUP_OBJECT (espace_client, treeview_vols_client, "treeview_vols_client");
  GLADE_HOOKUP_OBJECT (espace_client, vols_button, "vols_button");
  GLADE_HOOKUP_OBJECT (espace_client, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (espace_client, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (espace_client, image7, "image7");
  GLADE_HOOKUP_OBJECT (espace_client, label26, "label26");
  GLADE_HOOKUP_OBJECT (espace_client, Vols, "Vols");
  GLADE_HOOKUP_OBJECT (espace_client, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (espace_client, treeview_hotels_client, "treeview_hotels_client");
  GLADE_HOOKUP_OBJECT (espace_client, rechercher_hotel_entry, "rechercher_hotel_entry");
  GLADE_HOOKUP_OBJECT (espace_client, hotels_button, "hotels_button");
  GLADE_HOOKUP_OBJECT (espace_client, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (espace_client, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (espace_client, image5, "image5");
  GLADE_HOOKUP_OBJECT (espace_client, label21, "label21");
  GLADE_HOOKUP_OBJECT (espace_client, hist_payer_hotels, "hist_payer_hotels");
  GLADE_HOOKUP_OBJECT (espace_client, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (espace_client, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (espace_client, image16, "image16");
  GLADE_HOOKUP_OBJECT (espace_client, label104, "label104");
  GLADE_HOOKUP_OBJECT (espace_client, Hotels, "Hotels");
  GLADE_HOOKUP_OBJECT (espace_client, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (espace_client, treeview_location_voiture_client, "treeview_location_voiture_client");
  GLADE_HOOKUP_OBJECT (espace_client, rechercher_voiture_entry, "rechercher_voiture_entry");
  GLADE_HOOKUP_OBJECT (espace_client, voitures_button, "voitures_button");
  GLADE_HOOKUP_OBJECT (espace_client, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (espace_client, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (espace_client, image9, "image9");
  GLADE_HOOKUP_OBJECT (espace_client, label28, "label28");
  GLADE_HOOKUP_OBJECT (espace_client, Location_voitures, "Location_voitures");
  GLADE_HOOKUP_OBJECT (espace_client, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (espace_client, treeview_sejours_client, "treeview_sejours_client");
  GLADE_HOOKUP_OBJECT (espace_client, rechercher_sejours_entry, "rechercher_sejours_entry");
  GLADE_HOOKUP_OBJECT (espace_client, sejours_button, "sejours_button");
  GLADE_HOOKUP_OBJECT (espace_client, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (espace_client, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (espace_client, image8, "image8");
  GLADE_HOOKUP_OBJECT (espace_client, label27, "label27");
  GLADE_HOOKUP_OBJECT (espace_client, Sejours, "Sejours");
  GLADE_HOOKUP_OBJECT (espace_client, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (espace_client, treeview_reclamation_client, "treeview_reclamation_client");
  GLADE_HOOKUP_OBJECT (espace_client, entry_cin_reclamation, "entry_cin_reclamation");
  GLADE_HOOKUP_OBJECT (espace_client, ajouter_reclamation, "ajouter_reclamation");
  GLADE_HOOKUP_OBJECT (espace_client, supprimer_reclamation, "supprimer_reclamation");
  GLADE_HOOKUP_OBJECT (espace_client, entry_nom_reclamation, "entry_nom_reclamation");
  GLADE_HOOKUP_OBJECT (espace_client, entry_prenom_reclamation, "entry_prenom_reclamation");
  GLADE_HOOKUP_OBJECT (espace_client, entry_date_reclamation, "entry_date_reclamation");
  GLADE_HOOKUP_OBJECT (espace_client, entry_mes_reclamation, "entry_mes_reclamation");
  GLADE_HOOKUP_OBJECT (espace_client, modifier_reclamation, "modifier_reclamation");
  GLADE_HOOKUP_OBJECT (espace_client, Reclamation, "Reclamation");

  return espace_client;
}

GtkWidget*
create_payer_hotels (void)
{
  GtkWidget *payer_hotels;
  GtkWidget *fixed2;
  GtkWidget *prixh;
  GtkWidget *nomh;
  GtkWidget *paysh;
  GtkWidget *nbh;
  GtkWidget *toth;
  GtkWidget *adultesh;
  GtkWidget *enfantsh;
  GtkWidget *bebesh;
  GtkWidget *nbeh;
  GtkWidget *payerhotels;
  GtkWidget *nomhotel;
  GtkWidget *pays;
  GtkWidget *label49;
  GtkWidget *label6;
  GtkWidget *nombre_de_chambre;
  GtkWidget *label46;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *prix_total;
  GtkWidget *label83;

  payer_hotels = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (payer_hotels, 400, 650);
  gtk_window_set_title (GTK_WINDOW (payer_hotels), _("payer hotels"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (payer_hotels), fixed2);

  prixh = gtk_entry_new ();
  gtk_widget_show (prixh);
  gtk_fixed_put (GTK_FIXED (fixed2), prixh, 170, 240);
  gtk_widget_set_size_request (prixh, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (prixh), 8226);

  nomh = gtk_entry_new ();
  gtk_widget_show (nomh);
  gtk_fixed_put (GTK_FIXED (fixed2), nomh, 170, 60);
  gtk_widget_set_size_request (nomh, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomh), 8226);

  paysh = gtk_entry_new ();
  gtk_widget_show (paysh);
  gtk_fixed_put (GTK_FIXED (fixed2), paysh, 170, 120);
  gtk_widget_set_size_request (paysh, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (paysh), 8226);

  nbh = gtk_entry_new ();
  gtk_widget_show (nbh);
  gtk_fixed_put (GTK_FIXED (fixed2), nbh, 170, 300);
  gtk_widget_set_size_request (nbh, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbh), 8226);

  toth = gtk_entry_new ();
  gtk_widget_show (toth);
  gtk_fixed_put (GTK_FIXED (fixed2), toth, 170, 540);
  gtk_widget_set_size_request (toth, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (toth), 8226);

  adultesh = gtk_entry_new ();
  gtk_widget_show (adultesh);
  gtk_fixed_put (GTK_FIXED (fixed2), adultesh, 170, 360);
  gtk_widget_set_size_request (adultesh, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (adultesh), 8226);

  enfantsh = gtk_entry_new ();
  gtk_widget_show (enfantsh);
  gtk_fixed_put (GTK_FIXED (fixed2), enfantsh, 170, 420);
  gtk_widget_set_size_request (enfantsh, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (enfantsh), 8226);

  bebesh = gtk_entry_new ();
  gtk_widget_show (bebesh);
  gtk_fixed_put (GTK_FIXED (fixed2), bebesh, 170, 480);
  gtk_widget_set_size_request (bebesh, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (bebesh), 8226);

  nbeh = gtk_entry_new ();
  gtk_widget_show (nbeh);
  gtk_fixed_put (GTK_FIXED (fixed2), nbeh, 170, 180);
  gtk_widget_set_size_request (nbeh, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbeh), 8226);

  payerhotels = gtk_button_new_with_mnemonic (_("Payer"));
  gtk_widget_show (payerhotels);
  gtk_fixed_put (GTK_FIXED (fixed2), payerhotels, 264, 592);
  gtk_widget_set_size_request (payerhotels, 115, 40);

  nomhotel = gtk_label_new (_("Nom d'hotel :"));
  gtk_widget_show (nomhotel);
  gtk_fixed_put (GTK_FIXED (fixed2), nomhotel, 30, 70);
  gtk_widget_set_size_request (nomhotel, 112, 40);

  pays = gtk_label_new (_("Pays :"));
  gtk_widget_show (pays);
  gtk_fixed_put (GTK_FIXED (fixed2), pays, 30, 130);
  gtk_widget_set_size_request (pays, 103, 40);

  label49 = gtk_label_new (_("Nombre d'etoiles :"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed2), label49, 30, 180);
  gtk_widget_set_size_request (label49, 127, 40);

  label6 = gtk_label_new (_("Prix de la chambre"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 16, 240);
  gtk_widget_set_size_request (label6, 128, 40);

  nombre_de_chambre = gtk_label_new (_("Nombre de chambre :"));
  gtk_widget_show (nombre_de_chambre);
  gtk_fixed_put (GTK_FIXED (fixed2), nombre_de_chambre, 16, 300);
  gtk_widget_set_size_request (nombre_de_chambre, 150, 40);

  label46 = gtk_label_new (_("Adultes :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed2), label46, 24, 360);
  gtk_widget_set_size_request (label46, 104, 40);

  label47 = gtk_label_new (_("Enfants :"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed2), label47, 40, 420);
  gtk_widget_set_size_request (label47, 72, 40);

  label48 = gtk_label_new (_("bebes :"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed2), label48, 48, 480);
  gtk_widget_set_size_request (label48, 63, 40);

  prix_total = gtk_label_new (_("Prix Total :"));
  gtk_widget_show (prix_total);
  gtk_fixed_put (GTK_FIXED (fixed2), prix_total, 32, 540);
  gtk_widget_set_size_request (prix_total, 114, 40);

  label83 = gtk_label_new (_("<b><i><span foreground=\"darkcyan\" size=\"xx-large\">Sky Travel</span></i></b>"));
  gtk_widget_show (label83);
  gtk_fixed_put (GTK_FIXED (fixed2), label83, 24, 8);
  gtk_widget_set_size_request (label83, 171, 42);
  gtk_label_set_use_markup (GTK_LABEL (label83), TRUE);

  g_signal_connect ((gpointer) payerhotels, "clicked",
                    G_CALLBACK (on_payerhotels_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (payer_hotels, payer_hotels, "payer_hotels");
  GLADE_HOOKUP_OBJECT (payer_hotels, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (payer_hotels, prixh, "prixh");
  GLADE_HOOKUP_OBJECT (payer_hotels, nomh, "nomh");
  GLADE_HOOKUP_OBJECT (payer_hotels, paysh, "paysh");
  GLADE_HOOKUP_OBJECT (payer_hotels, nbh, "nbh");
  GLADE_HOOKUP_OBJECT (payer_hotels, toth, "toth");
  GLADE_HOOKUP_OBJECT (payer_hotels, adultesh, "adultesh");
  GLADE_HOOKUP_OBJECT (payer_hotels, enfantsh, "enfantsh");
  GLADE_HOOKUP_OBJECT (payer_hotels, bebesh, "bebesh");
  GLADE_HOOKUP_OBJECT (payer_hotels, nbeh, "nbeh");
  GLADE_HOOKUP_OBJECT (payer_hotels, payerhotels, "payerhotels");
  GLADE_HOOKUP_OBJECT (payer_hotels, nomhotel, "nomhotel");
  GLADE_HOOKUP_OBJECT (payer_hotels, pays, "pays");
  GLADE_HOOKUP_OBJECT (payer_hotels, label49, "label49");
  GLADE_HOOKUP_OBJECT (payer_hotels, label6, "label6");
  GLADE_HOOKUP_OBJECT (payer_hotels, nombre_de_chambre, "nombre_de_chambre");
  GLADE_HOOKUP_OBJECT (payer_hotels, label46, "label46");
  GLADE_HOOKUP_OBJECT (payer_hotels, label47, "label47");
  GLADE_HOOKUP_OBJECT (payer_hotels, label48, "label48");
  GLADE_HOOKUP_OBJECT (payer_hotels, prix_total, "prix_total");
  GLADE_HOOKUP_OBJECT (payer_hotels, label83, "label83");

  return payer_hotels;
}

GtkWidget*
create_Login (void)
{
  GtkWidget *Login;
  GtkWidget *fixed8;
  GtkWidget *identifiant_entry;
  GtkWidget *password_entry;
  GtkWidget *label25;
  GtkWidget *label24;
  GtkWidget *label23;
  GtkWidget *output_login;
  GtkWidget *login_button;

  Login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Login), _("window1"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (Login), fixed8);

  identifiant_entry = gtk_entry_new ();
  gtk_widget_show (identifiant_entry);
  gtk_fixed_put (GTK_FIXED (fixed8), identifiant_entry, 144, 64);
  gtk_widget_set_size_request (identifiant_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identifiant_entry), 8226);

  password_entry = gtk_entry_new ();
  gtk_widget_show (password_entry);
  gtk_fixed_put (GTK_FIXED (fixed8), password_entry, 144, 128);
  gtk_widget_set_size_request (password_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (password_entry), 8226);

  label25 = gtk_label_new (_("Sky travel"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed8), label25, 144, 16);
  gtk_widget_set_size_request (label25, 152, 24);

  label24 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed8), label24, 24, 128);
  gtk_widget_set_size_request (label24, 104, 24);

  label23 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed8), label23, 24, 72);
  gtk_widget_set_size_request (label23, 104, 16);

  output_login = gtk_label_new ("");
  gtk_widget_show (output_login);
  gtk_fixed_put (GTK_FIXED (fixed8), output_login, 120, 248);
  gtk_widget_set_size_request (output_login, 184, 24);

  login_button = gtk_button_new_with_mnemonic (_("s'identifier"));
  gtk_widget_show (login_button);
  gtk_fixed_put (GTK_FIXED (fixed8), login_button, 168, 192);
  gtk_widget_set_size_request (login_button, 104, 32);

  g_signal_connect ((gpointer) login_button, "clicked",
                    G_CALLBACK (on_login_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Login, Login, "Login");
  GLADE_HOOKUP_OBJECT (Login, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Login, identifiant_entry, "identifiant_entry");
  GLADE_HOOKUP_OBJECT (Login, password_entry, "password_entry");
  GLADE_HOOKUP_OBJECT (Login, label25, "label25");
  GLADE_HOOKUP_OBJECT (Login, label24, "label24");
  GLADE_HOOKUP_OBJECT (Login, label23, "label23");
  GLADE_HOOKUP_OBJECT (Login, output_login, "output_login");
  GLADE_HOOKUP_OBJECT (Login, login_button, "login_button");

  return Login;
}

GtkWidget*
create_payer_vols (void)
{
  GtkWidget *payer_vols;
  GtkWidget *fixed10;
  GtkWidget *fixed14;
  GtkWidget *departv;
  GtkWidget *destinationv;
  GtkWidget *datedepartv;
  GtkWidget *dateretourv;
  GtkWidget *nbvoyv;
  GtkWidget *classouv;
  GtkWidget *prixv;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *d;
  GtkWidget *dat;
  GtkWidget *nom;
  GtkWidget *classe;
  GtkWidget *pri;
  GtkWidget *label84;
  GtkWidget *payer_vols_button;

  payer_vols = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (payer_vols, 380, 520);
  gtk_window_set_title (GTK_WINDOW (payer_vols), _("payer vols"));

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (payer_vols), fixed10);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_fixed_put (GTK_FIXED (fixed10), fixed14, 0, 0);
  gtk_widget_set_size_request (fixed14, 0, 0);

  departv = gtk_entry_new ();
  gtk_widget_show (departv);
  gtk_fixed_put (GTK_FIXED (fixed14), departv, 168, 64);
  gtk_widget_set_size_request (departv, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (departv), 8226);

  destinationv = gtk_entry_new ();
  gtk_widget_show (destinationv);
  gtk_fixed_put (GTK_FIXED (fixed14), destinationv, 170, 120);
  gtk_widget_set_size_request (destinationv, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (destinationv), 8226);

  datedepartv = gtk_entry_new ();
  gtk_widget_show (datedepartv);
  gtk_fixed_put (GTK_FIXED (fixed14), datedepartv, 170, 180);
  gtk_widget_set_size_request (datedepartv, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (datedepartv), 8226);

  dateretourv = gtk_entry_new ();
  gtk_widget_show (dateretourv);
  gtk_fixed_put (GTK_FIXED (fixed14), dateretourv, 168, 240);
  gtk_widget_set_size_request (dateretourv, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (dateretourv), 8226);

  nbvoyv = gtk_entry_new ();
  gtk_widget_show (nbvoyv);
  gtk_fixed_put (GTK_FIXED (fixed14), nbvoyv, 170, 296);
  gtk_widget_set_size_request (nbvoyv, 199, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbvoyv), 8226);

  classouv = gtk_entry_new ();
  gtk_widget_show (classouv);
  gtk_fixed_put (GTK_FIXED (fixed14), classouv, 168, 360);
  gtk_widget_set_size_request (classouv, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (classouv), 8226);

  prixv = gtk_entry_new ();
  gtk_widget_show (prixv);
  gtk_fixed_put (GTK_FIXED (fixed14), prixv, 170, 420);
  gtk_widget_set_size_request (prixv, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (prixv), 8226);

  label51 = gtk_label_new (_("depart :"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed14), label51, 30, 70);
  gtk_widget_set_size_request (label51, 112, 40);

  label52 = gtk_label_new (_("destination :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed14), label52, 30, 130);
  gtk_widget_set_size_request (label52, 103, 40);

  d = gtk_label_new (_("datedepart :"));
  gtk_widget_show (d);
  gtk_fixed_put (GTK_FIXED (fixed14), d, 30, 180);
  gtk_widget_set_size_request (d, 127, 40);

  dat = gtk_label_new (_("dateretour:"));
  gtk_widget_show (dat);
  gtk_fixed_put (GTK_FIXED (fixed14), dat, 16, 240);
  gtk_widget_set_size_request (dat, 128, 40);

  nom = gtk_label_new (_("nombre des voyageurs:"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed14), nom, 8, 296);
  gtk_widget_set_size_request (nom, 161, 40);

  classe = gtk_label_new (_("classe souhait\303\251e :"));
  gtk_widget_show (classe);
  gtk_fixed_put (GTK_FIXED (fixed14), classe, 24, 360);
  gtk_widget_set_size_request (classe, 104, 40);

  pri = gtk_label_new (_("prix :"));
  gtk_widget_show (pri);
  gtk_fixed_put (GTK_FIXED (fixed14), pri, 40, 420);
  gtk_widget_set_size_request (pri, 72, 40);

  label84 = gtk_label_new (_("<b><i><span foreground=\"darkcyan\" size=\"xx-large\">Sky Travel</span></i></b>"));
  gtk_widget_show (label84);
  gtk_fixed_put (GTK_FIXED (fixed14), label84, 24, 8);
  gtk_widget_set_size_request (label84, 176, 41);
  gtk_label_set_use_markup (GTK_LABEL (label84), TRUE);

  payer_vols_button = gtk_button_new_with_mnemonic (_("Payer"));
  gtk_widget_show (payer_vols_button);
  gtk_fixed_put (GTK_FIXED (fixed14), payer_vols_button, 250, 460);
  gtk_widget_set_size_request (payer_vols_button, 115, 40);

  g_signal_connect ((gpointer) payer_vols_button, "clicked",
                    G_CALLBACK (on_payervols_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (payer_vols, payer_vols, "payer_vols");
  GLADE_HOOKUP_OBJECT (payer_vols, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (payer_vols, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (payer_vols, departv, "departv");
  GLADE_HOOKUP_OBJECT (payer_vols, destinationv, "destinationv");
  GLADE_HOOKUP_OBJECT (payer_vols, datedepartv, "datedepartv");
  GLADE_HOOKUP_OBJECT (payer_vols, dateretourv, "dateretourv");
  GLADE_HOOKUP_OBJECT (payer_vols, nbvoyv, "nbvoyv");
  GLADE_HOOKUP_OBJECT (payer_vols, classouv, "classouv");
  GLADE_HOOKUP_OBJECT (payer_vols, prixv, "prixv");
  GLADE_HOOKUP_OBJECT (payer_vols, label51, "label51");
  GLADE_HOOKUP_OBJECT (payer_vols, label52, "label52");
  GLADE_HOOKUP_OBJECT (payer_vols, d, "d");
  GLADE_HOOKUP_OBJECT (payer_vols, dat, "dat");
  GLADE_HOOKUP_OBJECT (payer_vols, nom, "nom");
  GLADE_HOOKUP_OBJECT (payer_vols, classe, "classe");
  GLADE_HOOKUP_OBJECT (payer_vols, pri, "pri");
  GLADE_HOOKUP_OBJECT (payer_vols, label84, "label84");
  GLADE_HOOKUP_OBJECT (payer_vols, payer_vols_button, "payer_vols_button");

  return payer_vols;
}

GtkWidget*
create_payer_sejours (void)
{
  GtkWidget *payer_sejours;
  GtkWidget *fixed11;
  GtkWidget *label54;
  GtkWidget *noms;
  GtkWidget *payss;
  GtkWidget *label55;
  GtkWidget *nbes;
  GtkWidget *label56;
  GtkWidget *prixs;
  GtkWidget *felxibilite;
  GtkWidget *tots;
  GtkWidget *label59;
  GtkWidget *label58;
  GtkWidget *label57;
  GtkWidget *label85;
  GtkWidget *payer_sejours_button;

  payer_sejours = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (payer_sejours, 380, 520);
  gtk_window_set_title (GTK_WINDOW (payer_sejours), _("payer sejours"));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (payer_sejours), fixed11);

  label54 = gtk_label_new (_("Nom d'hotel :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed11), label54, 30, 70);
  gtk_widget_set_size_request (label54, 112, 40);

  noms = gtk_entry_new ();
  gtk_widget_show (noms);
  gtk_fixed_put (GTK_FIXED (fixed11), noms, 170, 60);
  gtk_widget_set_size_request (noms, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (noms), 8226);

  payss = gtk_entry_new ();
  gtk_widget_show (payss);
  gtk_fixed_put (GTK_FIXED (fixed11), payss, 170, 120);
  gtk_widget_set_size_request (payss, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (payss), 8226);

  label55 = gtk_label_new (_("Pays :"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed11), label55, 30, 130);
  gtk_widget_set_size_request (label55, 103, 40);

  nbes = gtk_entry_new ();
  gtk_widget_show (nbes);
  gtk_fixed_put (GTK_FIXED (fixed11), nbes, 176, 184);
  gtk_widget_set_size_request (nbes, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbes), 8226);

  label56 = gtk_label_new (_("Nombre d'etoiles :"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed11), label56, 30, 180);
  gtk_widget_set_size_request (label56, 127, 40);

  prixs = gtk_entry_new ();
  gtk_widget_show (prixs);
  gtk_fixed_put (GTK_FIXED (fixed11), prixs, 168, 240);
  gtk_widget_set_size_request (prixs, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (prixs), 8226);

  felxibilite = gtk_entry_new ();
  gtk_widget_show (felxibilite);
  gtk_fixed_put (GTK_FIXED (fixed11), felxibilite, 170, 300);
  gtk_widget_set_size_request (felxibilite, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (felxibilite), 8226);

  tots = gtk_entry_new ();
  gtk_widget_show (tots);
  gtk_fixed_put (GTK_FIXED (fixed11), tots, 170, 360);
  gtk_widget_set_size_request (tots, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (tots), 8226);

  label59 = gtk_label_new (_("Total :"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed11), label59, 24, 360);
  gtk_widget_set_size_request (label59, 104, 40);

  label58 = gtk_label_new (_("Flexibilit\303\251 :"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed11), label58, 16, 300);
  gtk_widget_set_size_request (label58, 150, 40);

  label57 = gtk_label_new (_("Prix de la nuit :"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed11), label57, 16, 240);
  gtk_widget_set_size_request (label57, 128, 40);

  label85 = gtk_label_new (_("<b><i><span foreground=\"darkcyan\" size=\"xx-large\">Sky Travel</span></i></b>"));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (fixed11), label85, 24, 8);
  gtk_widget_set_size_request (label85, 160, 41);
  gtk_label_set_use_markup (GTK_LABEL (label85), TRUE);

  payer_sejours_button = gtk_button_new_with_mnemonic (_("Payer"));
  gtk_widget_show (payer_sejours_button);
  gtk_fixed_put (GTK_FIXED (fixed11), payer_sejours_button, 250, 460);
  gtk_widget_set_size_request (payer_sejours_button, 115, 40);

  g_signal_connect ((gpointer) payer_sejours_button, "clicked",
                    G_CALLBACK (on_payer_sejours_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (payer_sejours, payer_sejours, "payer_sejours");
  GLADE_HOOKUP_OBJECT (payer_sejours, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (payer_sejours, label54, "label54");
  GLADE_HOOKUP_OBJECT (payer_sejours, noms, "noms");
  GLADE_HOOKUP_OBJECT (payer_sejours, payss, "payss");
  GLADE_HOOKUP_OBJECT (payer_sejours, label55, "label55");
  GLADE_HOOKUP_OBJECT (payer_sejours, nbes, "nbes");
  GLADE_HOOKUP_OBJECT (payer_sejours, label56, "label56");
  GLADE_HOOKUP_OBJECT (payer_sejours, prixs, "prixs");
  GLADE_HOOKUP_OBJECT (payer_sejours, felxibilite, "felxibilite");
  GLADE_HOOKUP_OBJECT (payer_sejours, tots, "tots");
  GLADE_HOOKUP_OBJECT (payer_sejours, label59, "label59");
  GLADE_HOOKUP_OBJECT (payer_sejours, label58, "label58");
  GLADE_HOOKUP_OBJECT (payer_sejours, label57, "label57");
  GLADE_HOOKUP_OBJECT (payer_sejours, label85, "label85");
  GLADE_HOOKUP_OBJECT (payer_sejours, payer_sejours_button, "payer_sejours_button");

  return payer_sejours;
}

GtkWidget*
create_payer_location_voitures (void)
{
  GtkWidget *payer_location_voitures;
  GtkWidget *fixed12;
  GtkWidget *payl;
  GtkWidget *vil;
  GtkWidget *agel;
  GtkWidget *modl;
  GtkWidget *pril;
  GtkWidget *dpcl;
  GtkWidget *nbjl;
  GtkWidget *label61;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *label67;
  GtkWidget *totl;
  GtkWidget *label68;
  GtkWidget *label88;
  GtkWidget *payerlocationvoitures;

  payer_location_voitures = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (payer_location_voitures, 380, 520);
  gtk_window_set_title (GTK_WINDOW (payer_location_voitures), _("payer location voitures"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (payer_location_voitures), fixed12);

  payl = gtk_entry_new ();
  gtk_widget_show (payl);
  gtk_fixed_put (GTK_FIXED (fixed12), payl, 170, 60);
  gtk_widget_set_size_request (payl, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (payl), 8226);

  vil = gtk_entry_new ();
  gtk_widget_show (vil);
  gtk_fixed_put (GTK_FIXED (fixed12), vil, 170, 120);
  gtk_widget_set_size_request (vil, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (vil), 8226);

  agel = gtk_entry_new ();
  gtk_widget_show (agel);
  gtk_fixed_put (GTK_FIXED (fixed12), agel, 170, 180);
  gtk_widget_set_size_request (agel, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (agel), 8226);

  modl = gtk_entry_new ();
  gtk_widget_show (modl);
  gtk_fixed_put (GTK_FIXED (fixed12), modl, 170, 240);
  gtk_widget_set_size_request (modl, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (modl), 8226);

  pril = gtk_entry_new ();
  gtk_widget_show (pril);
  gtk_fixed_put (GTK_FIXED (fixed12), pril, 170, 300);
  gtk_widget_set_size_request (pril, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (pril), 8226);

  dpcl = gtk_entry_new ();
  gtk_widget_show (dpcl);
  gtk_fixed_put (GTK_FIXED (fixed12), dpcl, 170, 360);
  gtk_widget_set_size_request (dpcl, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (dpcl), 8226);

  nbjl = gtk_entry_new ();
  gtk_widget_show (nbjl);
  gtk_fixed_put (GTK_FIXED (fixed12), nbjl, 170, 420);
  gtk_widget_set_size_request (nbjl, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbjl), 8226);

  label61 = gtk_label_new (_("pays:"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed12), label61, 30, 70);
  gtk_widget_set_size_request (label61, 112, 40);

  label62 = gtk_label_new (_("ville :"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed12), label62, 30, 130);
  gtk_widget_set_size_request (label62, 103, 40);

  label63 = gtk_label_new (_("agence :"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed12), label63, 30, 180);
  gtk_widget_set_size_request (label63, 127, 40);

  label64 = gtk_label_new (_("modele :"));
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed12), label64, 16, 240);
  gtk_widget_set_size_request (label64, 128, 40);

  label65 = gtk_label_new (_("prix par jour:"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed12), label65, 16, 300);
  gtk_widget_set_size_request (label65, 150, 40);

  label66 = gtk_label_new (_("date pe prise en charge :"));
  gtk_widget_show (label66);
  gtk_fixed_put (GTK_FIXED (fixed12), label66, 5, 360);
  gtk_widget_set_size_request (label66, 168, 40);

  label67 = gtk_label_new (_("nombre de jours :"));
  gtk_widget_show (label67);
  gtk_fixed_put (GTK_FIXED (fixed12), label67, 23, 420);
  gtk_widget_set_size_request (label67, 127, 40);

  totl = gtk_entry_new ();
  gtk_widget_show (totl);
  gtk_fixed_put (GTK_FIXED (fixed12), totl, 170, 480);
  gtk_widget_set_size_request (totl, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (totl), 8226);

  label68 = gtk_label_new (_("total :"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed12), label68, 48, 480);
  gtk_widget_set_size_request (label68, 63, 40);

  label88 = gtk_label_new (_("<b><i><span foreground=\"darkcyan\" size=\"xx-large\">Sky Travel</span></i></b>"));
  gtk_widget_show (label88);
  gtk_fixed_put (GTK_FIXED (fixed12), label88, 24, 8);
  gtk_widget_set_size_request (label88, 178, 45);
  gtk_label_set_use_markup (GTK_LABEL (label88), TRUE);

  payerlocationvoitures = gtk_button_new_with_mnemonic (_("Payer"));
  gtk_widget_show (payerlocationvoitures);
  gtk_fixed_put (GTK_FIXED (fixed12), payerlocationvoitures, 248, 592);
  gtk_widget_set_size_request (payerlocationvoitures, 115, 40);

  g_signal_connect ((gpointer) payerlocationvoitures, "clicked",
                    G_CALLBACK (on_payerlocationvoitures_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (payer_location_voitures, payer_location_voitures, "payer_location_voitures");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, payl, "payl");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, vil, "vil");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, agel, "agel");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, modl, "modl");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, pril, "pril");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, dpcl, "dpcl");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, nbjl, "nbjl");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label61, "label61");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label62, "label62");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label63, "label63");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label64, "label64");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label65, "label65");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label66, "label66");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label67, "label67");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, totl, "totl");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label68, "label68");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, label88, "label88");
  GLADE_HOOKUP_OBJECT (payer_location_voitures, payerlocationvoitures, "payerlocationvoitures");

  return payer_location_voitures;
}

GtkWidget*
create_profile (void)
{
  GtkWidget *profile;
  GtkWidget *fixed13;
  GtkWidget *nomp;
  GtkWidget *prenomp;
  GtkWidget *sexep;
  GtkWidget *datep;
  GtkWidget *telp;
  GtkWidget *adressep;
  GtkWidget *mdpp;
  GtkWidget *label87;
  GtkWidget *cinp;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label69;
  GtkWidget *label70;
  GtkWidget *label71;
  GtkWidget *label72;
  GtkWidget *label73;
  GtkWidget *label105;
  GtkWidget *retour;
  GtkWidget *modifier;

  profile = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (profile, 400, 650);
  gtk_window_set_title (GTK_WINDOW (profile), _("profile"));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (profile), fixed13);

  nomp = gtk_entry_new ();
  gtk_widget_show (nomp);
  gtk_fixed_put (GTK_FIXED (fixed13), nomp, 168, 48);
  gtk_widget_set_size_request (nomp, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomp), 8226);

  prenomp = gtk_entry_new ();
  gtk_widget_show (prenomp);
  gtk_fixed_put (GTK_FIXED (fixed13), prenomp, 168, 96);
  gtk_widget_set_size_request (prenomp, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenomp), 8226);

  sexep = gtk_entry_new ();
  gtk_widget_show (sexep);
  gtk_fixed_put (GTK_FIXED (fixed13), sexep, 168, 144);
  gtk_widget_set_size_request (sexep, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (sexep), 8226);

  datep = gtk_entry_new ();
  gtk_widget_show (datep);
  gtk_fixed_put (GTK_FIXED (fixed13), datep, 168, 192);
  gtk_widget_set_size_request (datep, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (datep), 8226);

  telp = gtk_entry_new ();
  gtk_widget_show (telp);
  gtk_fixed_put (GTK_FIXED (fixed13), telp, 168, 240);
  gtk_widget_set_size_request (telp, 199, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (telp), 8226);

  adressep = gtk_entry_new ();
  gtk_widget_show (adressep);
  gtk_fixed_put (GTK_FIXED (fixed13), adressep, 168, 296);
  gtk_widget_set_size_request (adressep, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (adressep), 8226);

  mdpp = gtk_entry_new ();
  gtk_widget_show (mdpp);
  gtk_fixed_put (GTK_FIXED (fixed13), mdpp, 168, 344);
  gtk_widget_set_size_request (mdpp, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (mdpp), 8226);

  label87 = gtk_label_new (_("<b><i><span foreground=\"darkcyan\" size=\"xx-large\">Sky Travel</span></i></b>"));
  gtk_widget_show (label87);
  gtk_fixed_put (GTK_FIXED (fixed13), label87, 8, 8);
  gtk_widget_set_size_request (label87, 156, 40);
  gtk_label_set_use_markup (GTK_LABEL (label87), TRUE);

  cinp = gtk_entry_new ();
  gtk_widget_show (cinp);
  gtk_fixed_put (GTK_FIXED (fixed13), cinp, 168, 400);
  gtk_widget_set_size_request (cinp, 201, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinp), 8226);

  label44 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed13), label44, 56, 56);
  gtk_widget_set_size_request (label44, 99, 44);

  label45 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed13), label45, 72, 96);
  gtk_widget_set_size_request (label45, 80, 44);

  label69 = gtk_label_new (_("sexe:"));
  gtk_widget_show (label69);
  gtk_fixed_put (GTK_FIXED (fixed13), label69, 40, 144);
  gtk_widget_set_size_request (label69, 127, 44);

  label70 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label70);
  gtk_fixed_put (GTK_FIXED (fixed13), label70, 40, 192);
  gtk_widget_set_size_request (label70, 128, 44);

  label71 = gtk_label_new (_("tel:"));
  gtk_widget_show (label71);
  gtk_fixed_put (GTK_FIXED (fixed13), label71, 16, 232);
  gtk_widget_set_size_request (label71, 161, 44);

  label72 = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label72);
  gtk_fixed_put (GTK_FIXED (fixed13), label72, 40, 288);
  gtk_widget_set_size_request (label72, 99, 44);

  label73 = gtk_label_new (_(" Mot de passe:"));
  gtk_widget_show (label73);
  gtk_fixed_put (GTK_FIXED (fixed13), label73, 40, 344);
  gtk_widget_set_size_request (label73, 99, 44);

  label105 = gtk_label_new (_("cin:"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed13), label105, 72, 400);
  gtk_widget_set_size_request (label105, 57, 25);

  retour = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed13), retour, 48, 464);
  gtk_widget_set_size_request (retour, 95, 40);

  modifier = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed13), modifier, 304, 472);
  gtk_widget_set_size_request (modifier, 100, 40);

  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (profile, profile, "profile");
  GLADE_HOOKUP_OBJECT (profile, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (profile, nomp, "nomp");
  GLADE_HOOKUP_OBJECT (profile, prenomp, "prenomp");
  GLADE_HOOKUP_OBJECT (profile, sexep, "sexep");
  GLADE_HOOKUP_OBJECT (profile, datep, "datep");
  GLADE_HOOKUP_OBJECT (profile, telp, "telp");
  GLADE_HOOKUP_OBJECT (profile, adressep, "adressep");
  GLADE_HOOKUP_OBJECT (profile, mdpp, "mdpp");
  GLADE_HOOKUP_OBJECT (profile, label87, "label87");
  GLADE_HOOKUP_OBJECT (profile, cinp, "cinp");
  GLADE_HOOKUP_OBJECT (profile, label44, "label44");
  GLADE_HOOKUP_OBJECT (profile, label45, "label45");
  GLADE_HOOKUP_OBJECT (profile, label69, "label69");
  GLADE_HOOKUP_OBJECT (profile, label70, "label70");
  GLADE_HOOKUP_OBJECT (profile, label71, "label71");
  GLADE_HOOKUP_OBJECT (profile, label72, "label72");
  GLADE_HOOKUP_OBJECT (profile, label73, "label73");
  GLADE_HOOKUP_OBJECT (profile, label105, "label105");
  GLADE_HOOKUP_OBJECT (profile, retour, "retour");
  GLADE_HOOKUP_OBJECT (profile, modifier, "modifier");

  return profile;
}

GtkWidget*
create_Modification_des_informations (void)
{
  GtkWidget *Modification_des_informations;
  GtkWidget *fixed15;
  GtkWidget *label74;
  GtkWidget *label75;
  GtkWidget *label76;
  GtkWidget *label77;
  GtkWidget *label79;
  GtkWidget *label80;
  GtkWidget *nomp_mod;
  GtkWidget *prenomp_mod;
  GtkWidget *sexep_mod;
  GtkWidget *datep_mod;
  GtkWidget *telp_mod;
  GtkWidget *adressep_mod;
  GtkWidget *mdpp_mod;
  GtkWidget *label89;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *cinp_mod;
  GtkWidget *label106;
  GtkWidget *label78;

  Modification_des_informations = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modification_des_informations), _("Modification_des_informations"));

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_container_add (GTK_CONTAINER (Modification_des_informations), fixed15);

  label74 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label74);
  gtk_fixed_put (GTK_FIXED (fixed15), label74, 64, 64);
  gtk_widget_set_size_request (label74, 99, 44);

  label75 = gtk_label_new (_("Prenom :"));
  gtk_widget_show (label75);
  gtk_fixed_put (GTK_FIXED (fixed15), label75, 64, 120);
  gtk_widget_set_size_request (label75, 80, 44);

  label76 = gtk_label_new (_("sexe:"));
  gtk_widget_show (label76);
  gtk_fixed_put (GTK_FIXED (fixed15), label76, 30, 180);
  gtk_widget_set_size_request (label76, 127, 44);

  label77 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label77);
  gtk_fixed_put (GTK_FIXED (fixed15), label77, 16, 240);
  gtk_widget_set_size_request (label77, 128, 44);

  label79 = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label79);
  gtk_fixed_put (GTK_FIXED (fixed15), label79, 24, 360);
  gtk_widget_set_size_request (label79, 99, 44);

  label80 = gtk_label_new (_(" Mot de passe:"));
  gtk_widget_show (label80);
  gtk_fixed_put (GTK_FIXED (fixed15), label80, 40, 416);
  gtk_widget_set_size_request (label80, 99, 44);

  nomp_mod = gtk_entry_new ();
  gtk_widget_show (nomp_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), nomp_mod, 168, 72);
  gtk_widget_set_size_request (nomp_mod, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomp_mod), 8226);

  prenomp_mod = gtk_entry_new ();
  gtk_widget_show (prenomp_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), prenomp_mod, 170, 120);
  gtk_widget_set_size_request (prenomp_mod, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenomp_mod), 8226);

  sexep_mod = gtk_entry_new ();
  gtk_widget_show (sexep_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), sexep_mod, 168, 184);
  gtk_widget_set_size_request (sexep_mod, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (sexep_mod), 8226);

  datep_mod = gtk_entry_new ();
  gtk_widget_show (datep_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), datep_mod, 168, 240);
  gtk_widget_set_size_request (datep_mod, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (datep_mod), 8226);

  telp_mod = gtk_entry_new ();
  gtk_widget_show (telp_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), telp_mod, 168, 296);
  gtk_widget_set_size_request (telp_mod, 199, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (telp_mod), 8226);

  adressep_mod = gtk_entry_new ();
  gtk_widget_show (adressep_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), adressep_mod, 168, 360);
  gtk_widget_set_size_request (adressep_mod, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (adressep_mod), 8226);

  mdpp_mod = gtk_entry_new ();
  gtk_widget_show (mdpp_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), mdpp_mod, 170, 420);
  gtk_widget_set_size_request (mdpp_mod, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (mdpp_mod), 8226);

  label89 = gtk_label_new (_("<b><i><span foreground=\"darkcyan\" size=\"xx-large\">Sky Travel</span></i></b>"));
  gtk_widget_show (label89);
  gtk_fixed_put (GTK_FIXED (fixed15), label89, 26, 16);
  gtk_widget_set_size_request (label89, 158, 26);
  gtk_label_set_use_markup (GTK_LABEL (label89), TRUE);

  button10 = gtk_button_new_with_mnemonic (_("valider"));
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed15), button10, 368, 536);
  gtk_widget_set_size_request (button10, 100, 40);

  button11 = gtk_button_new_with_mnemonic (_("annuler"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed15), button11, 56, 528);
  gtk_widget_set_size_request (button11, 95, 40);

  cinp_mod = gtk_entry_new ();
  gtk_widget_show (cinp_mod);
  gtk_fixed_put (GTK_FIXED (fixed15), cinp_mod, 168, 472);
  gtk_widget_set_size_request (cinp_mod, 201, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinp_mod), 8226);

  label106 = gtk_label_new (_("cin:"));
  gtk_widget_show (label106);
  gtk_fixed_put (GTK_FIXED (fixed15), label106, 64, 472);
  gtk_widget_set_size_request (label106, 57, 39);

  label78 = gtk_label_new (_("tel:"));
  gtk_widget_show (label78);
  gtk_fixed_put (GTK_FIXED (fixed15), label78, 8, 296);
  gtk_widget_set_size_request (label78, 161, 44);

  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_retourprofile_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modification_des_informations, Modification_des_informations, "Modification_des_informations");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label74, "label74");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label75, "label75");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label76, "label76");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label77, "label77");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label79, "label79");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label80, "label80");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, nomp_mod, "nomp_mod");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, prenomp_mod, "prenomp_mod");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, sexep_mod, "sexep_mod");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, datep_mod, "datep_mod");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, telp_mod, "telp_mod");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, adressep_mod, "adressep_mod");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, mdpp_mod, "mdpp_mod");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label89, "label89");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, button10, "button10");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, button11, "button11");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, cinp_mod, "cinp_mod");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label106, "label106");
  GLADE_HOOKUP_OBJECT (Modification_des_informations, label78, "label78");

  return Modification_des_informations;
}

GtkWidget*
create_window_ajouter_recmlamation (void)
{
  GtkWidget *window_ajouter_recmlamation;
  GtkWidget *fixed16;
  GtkWidget *nomc;
  GtkWidget *label29;
  GtkWidget *prenomc;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *cinc;
  GtkWidget *label32;
  GtkWidget *messagec;
  GtkWidget *datec;
  GtkWidget *label34;
  GtkWidget *envoyer;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label33;

  window_ajouter_recmlamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_ajouter_recmlamation), _("ajouter une reclamation"));

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_container_add (GTK_CONTAINER (window_ajouter_recmlamation), fixed16);

  nomc = gtk_entry_new ();
  gtk_widget_show (nomc);
  gtk_fixed_put (GTK_FIXED (fixed16), nomc, 140, 10);
  gtk_widget_set_size_request (nomc, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (nomc), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomc), 8226);

  label29 = gtk_label_new (_("NOM  : "));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed16), label29, 40, 10);
  gtk_widget_set_size_request (label29, 60, 40);

  prenomc = gtk_entry_new ();
  gtk_widget_show (prenomc);
  gtk_fixed_put (GTK_FIXED (fixed16), prenomc, 144, 72);
  gtk_widget_set_size_request (prenomc, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (prenomc), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenomc), 8226);

  label30 = gtk_label_new (_("PRENOM : "));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed16), label30, 40, 70);
  gtk_widget_set_size_request (label30, 80, 40);

  label31 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed16), label31, 40, 130);
  gtk_widget_set_size_request (label31, 60, 40);

  cinc = gtk_entry_new ();
  gtk_widget_show (cinc);
  gtk_fixed_put (GTK_FIXED (fixed16), cinc, 140, 130);
  gtk_widget_set_size_request (cinc, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (cinc), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinc), 8226);

  label32 = gtk_label_new (_("MESSAGE :"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed16), label32, 40, 208);
  gtk_widget_set_size_request (label32, 80, 40);

  messagec = gtk_entry_new ();
  gtk_widget_show (messagec);
  gtk_fixed_put (GTK_FIXED (fixed16), messagec, 140, 190);
  gtk_widget_set_size_request (messagec, 650, 110);
  gtk_entry_set_max_length (GTK_ENTRY (messagec), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (messagec), 8226);

  datec = gtk_entry_new ();
  gtk_widget_show (datec);
  gtk_fixed_put (GTK_FIXED (fixed16), datec, 488, 72);
  gtk_widget_set_size_request (datec, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (datec), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (datec), 8226);

  label34 = gtk_label_new (_("DATE : "));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed16), label34, 400, 70);
  gtk_widget_set_size_request (label34, 80, 40);

  envoyer = gtk_button_new ();
  gtk_widget_show (envoyer);
  gtk_fixed_put (GTK_FIXED (fixed16), envoyer, 705, 307);
  gtk_widget_set_size_request (envoyer, 124, 37);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (envoyer), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-media-next", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Envoyer"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox10), label33, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) envoyer, "clicked",
                    G_CALLBACK (on_envoyer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajouter_recmlamation, window_ajouter_recmlamation, "window_ajouter_recmlamation");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, nomc, "nomc");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, label29, "label29");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, prenomc, "prenomc");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, label30, "label30");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, label31, "label31");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, cinc, "cinc");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, label32, "label32");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, messagec, "messagec");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, datec, "datec");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, label34, "label34");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, envoyer, "envoyer");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_ajouter_recmlamation, label33, "label33");

  return window_ajouter_recmlamation;
}

GtkWidget*
create_modifier_reclamation_client (void)
{
  GtkWidget *modifier_reclamation_client;
  GtkWidget *fixed17;
  GtkWidget *nomc_modif;
  GtkWidget *label90;
  GtkWidget *prenomc_modif;
  GtkWidget *label91;
  GtkWidget *label92;
  GtkWidget *cinc_modif;
  GtkWidget *label93;
  GtkWidget *mesc_modif;
  GtkWidget *datec_modif;
  GtkWidget *label94;
  GtkWidget *valider_reclamation;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label95;

  modifier_reclamation_client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_reclamation_client), _("modifier_reclamation"));

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_container_add (GTK_CONTAINER (modifier_reclamation_client), fixed17);

  nomc_modif = gtk_entry_new ();
  gtk_widget_show (nomc_modif);
  gtk_fixed_put (GTK_FIXED (fixed17), nomc_modif, 136, 8);
  gtk_widget_set_size_request (nomc_modif, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (nomc_modif), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomc_modif), 8226);

  label90 = gtk_label_new (_("NOM  : "));
  gtk_widget_show (label90);
  gtk_fixed_put (GTK_FIXED (fixed17), label90, 40, 10);
  gtk_widget_set_size_request (label90, 60, 40);

  prenomc_modif = gtk_entry_new ();
  gtk_widget_show (prenomc_modif);
  gtk_fixed_put (GTK_FIXED (fixed17), prenomc_modif, 144, 72);
  gtk_widget_set_size_request (prenomc_modif, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (prenomc_modif), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (prenomc_modif), 8226);

  label91 = gtk_label_new (_("PRENOM : "));
  gtk_widget_show (label91);
  gtk_fixed_put (GTK_FIXED (fixed17), label91, 40, 70);
  gtk_widget_set_size_request (label91, 80, 40);

  label92 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label92);
  gtk_fixed_put (GTK_FIXED (fixed17), label92, 40, 130);
  gtk_widget_set_size_request (label92, 60, 40);

  cinc_modif = gtk_entry_new ();
  gtk_widget_show (cinc_modif);
  gtk_fixed_put (GTK_FIXED (fixed17), cinc_modif, 140, 130);
  gtk_widget_set_size_request (cinc_modif, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (cinc_modif), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (cinc_modif), 8226);

  label93 = gtk_label_new (_("MESSAGE :"));
  gtk_widget_show (label93);
  gtk_fixed_put (GTK_FIXED (fixed17), label93, 40, 208);
  gtk_widget_set_size_request (label93, 80, 40);

  mesc_modif = gtk_entry_new ();
  gtk_widget_show (mesc_modif);
  gtk_fixed_put (GTK_FIXED (fixed17), mesc_modif, 136, 192);
  gtk_widget_set_size_request (mesc_modif, 650, 110);
  gtk_entry_set_max_length (GTK_ENTRY (mesc_modif), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (mesc_modif), 8226);

  datec_modif = gtk_entry_new ();
  gtk_widget_show (datec_modif);
  gtk_fixed_put (GTK_FIXED (fixed17), datec_modif, 488, 72);
  gtk_widget_set_size_request (datec_modif, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (datec_modif), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (datec_modif), 8226);

  label94 = gtk_label_new (_("DATE : "));
  gtk_widget_show (label94);
  gtk_fixed_put (GTK_FIXED (fixed17), label94, 400, 70);
  gtk_widget_set_size_request (label94, 80, 40);

  valider_reclamation = gtk_button_new ();
  gtk_widget_show (valider_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed17), valider_reclamation, 705, 307);
  gtk_widget_set_size_request (valider_reclamation, 124, 37);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (valider_reclamation), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox12), label95, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) valider_reclamation, "clicked",
                    G_CALLBACK (on_valider_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_reclamation_client, modifier_reclamation_client, "modifier_reclamation_client");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, nomc_modif, "nomc_modif");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, label90, "label90");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, prenomc_modif, "prenomc_modif");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, label91, "label91");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, label92, "label92");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, cinc_modif, "cinc_modif");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, label93, "label93");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, mesc_modif, "mesc_modif");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, datec_modif, "datec_modif");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, label94, "label94");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, valider_reclamation, "valider_reclamation");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, image12, "image12");
  GLADE_HOOKUP_OBJECT (modifier_reclamation_client, label95, "label95");

  return modifier_reclamation_client;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed18;
  GtkWidget *entry25;
  GtkWidget *label96;
  GtkWidget *entry26;
  GtkWidget *label97;
  GtkWidget *label98;
  GtkWidget *entry27;
  GtkWidget *label99;
  GtkWidget *entry28;
  GtkWidget *entry29;
  GtkWidget *label100;
  GtkWidget *button12;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label101;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window1"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (window2), fixed18);

  entry25 = gtk_entry_new ();
  gtk_widget_show (entry25);
  gtk_fixed_put (GTK_FIXED (fixed18), entry25, 140, 10);
  gtk_widget_set_size_request (entry25, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (entry25), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry25), 8226);

  label96 = gtk_label_new (_("NOM  : "));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed18), label96, 40, 10);
  gtk_widget_set_size_request (label96, 60, 40);

  entry26 = gtk_entry_new ();
  gtk_widget_show (entry26);
  gtk_fixed_put (GTK_FIXED (fixed18), entry26, 144, 72);
  gtk_widget_set_size_request (entry26, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (entry26), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry26), 8226);

  label97 = gtk_label_new (_("PRENOM : "));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed18), label97, 40, 70);
  gtk_widget_set_size_request (label97, 80, 40);

  label98 = gtk_label_new (_("CIN : "));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed18), label98, 40, 130);
  gtk_widget_set_size_request (label98, 60, 40);

  entry27 = gtk_entry_new ();
  gtk_widget_show (entry27);
  gtk_fixed_put (GTK_FIXED (fixed18), entry27, 140, 130);
  gtk_widget_set_size_request (entry27, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (entry27), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry27), 8226);

  label99 = gtk_label_new (_("MESSAGE :"));
  gtk_widget_show (label99);
  gtk_fixed_put (GTK_FIXED (fixed18), label99, 40, 208);
  gtk_widget_set_size_request (label99, 80, 40);

  entry28 = gtk_entry_new ();
  gtk_widget_show (entry28);
  gtk_fixed_put (GTK_FIXED (fixed18), entry28, 136, 192);
  gtk_widget_set_size_request (entry28, 650, 110);
  gtk_entry_set_max_length (GTK_ENTRY (entry28), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry28), 8226);

  entry29 = gtk_entry_new ();
  gtk_widget_show (entry29);
  gtk_fixed_put (GTK_FIXED (fixed18), entry29, 488, 72);
  gtk_widget_set_size_request (entry29, 200, 40);
  gtk_entry_set_max_length (GTK_ENTRY (entry29), 300);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry29), 8226);

  label100 = gtk_label_new (_("DATE : "));
  gtk_widget_show (label100);
  gtk_fixed_put (GTK_FIXED (fixed18), label100, 400, 70);
  gtk_widget_set_size_request (label100, 80, 40);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed18), button12, 705, 307);
  gtk_widget_set_size_request (button12, 124, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button12), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label101 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label101);
  gtk_box_pack_start (GTK_BOX (hbox13), label101, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_valider_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (window2, entry25, "entry25");
  GLADE_HOOKUP_OBJECT (window2, label96, "label96");
  GLADE_HOOKUP_OBJECT (window2, entry26, "entry26");
  GLADE_HOOKUP_OBJECT (window2, label97, "label97");
  GLADE_HOOKUP_OBJECT (window2, label98, "label98");
  GLADE_HOOKUP_OBJECT (window2, entry27, "entry27");
  GLADE_HOOKUP_OBJECT (window2, label99, "label99");
  GLADE_HOOKUP_OBJECT (window2, entry28, "entry28");
  GLADE_HOOKUP_OBJECT (window2, entry29, "entry29");
  GLADE_HOOKUP_OBJECT (window2, label100, "label100");
  GLADE_HOOKUP_OBJECT (window2, button12, "button12");
  GLADE_HOOKUP_OBJECT (window2, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window2, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window2, image13, "image13");
  GLADE_HOOKUP_OBJECT (window2, label101, "label101");

  return window2;
}

GtkWidget*
create_historique_payer_hotels (void)
{
  GtkWidget *historique_payer_hotels;
  GtkWidget *fixed19;
  GtkWidget *treeview_payer_hotels;
  GtkWidget *modifier_payer_hotels;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label102;
  GtkWidget *nom_hotels;
  GtkWidget *supprimer_payer_hotels;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label103;
  GtkWidget *pays_hotels;
  GtkWidget *nbe_hotels;
  GtkWidget *prix_hotels;
  GtkWidget *adultes_hotels;
  GtkWidget *nbch_hotels;
  GtkWidget *tot_hotels;
  GtkWidget *enfants_hotels;
  GtkWidget *bebes_hotels;

  historique_payer_hotels = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (historique_payer_hotels), _("historique"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (historique_payer_hotels), fixed19);

  treeview_payer_hotels = gtk_tree_view_new ();
  gtk_widget_show (treeview_payer_hotels);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview_payer_hotels, 8, 40);
  gtk_widget_set_size_request (treeview_payer_hotels, 560, 240);

  modifier_payer_hotels = gtk_button_new ();
  gtk_widget_show (modifier_payer_hotels);
  gtk_fixed_put (GTK_FIXED (fixed19), modifier_payer_hotels, 248, 320);
  gtk_widget_set_size_request (modifier_payer_hotels, 111, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (modifier_payer_hotels), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox14), label102, FALSE, FALSE, 0);

  nom_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), nom_hotels, 568, 152);
  gtk_widget_set_size_request (nom_hotels, 19, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_hotels), 8226);

  supprimer_payer_hotels = gtk_button_new ();
  gtk_widget_show (supprimer_payer_hotels);
  gtk_fixed_put (GTK_FIXED (fixed19), supprimer_payer_hotels, 376, 320);
  gtk_widget_set_size_request (supprimer_payer_hotels, 99, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (supprimer_payer_hotels), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox15), label103, FALSE, FALSE, 0);

  pays_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), pays_hotels, 592, 80);
  gtk_widget_set_size_request (pays_hotels, 17, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (pays_hotels), 8226);

  nbe_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), nbe_hotels, 616, 112);
  gtk_widget_set_size_request (nbe_hotels, 17, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbe_hotels), 8226);

  prix_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), prix_hotels, 608, 152);
  gtk_widget_set_size_request (prix_hotels, 17, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (prix_hotels), 8226);

  adultes_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), adultes_hotels, 584, 240);
  gtk_widget_set_size_request (adultes_hotels, 17, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (adultes_hotels), 8226);

  nbch_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), nbch_hotels, 576, 200);
  gtk_widget_set_size_request (nbch_hotels, 17, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbch_hotels), 8226);

  tot_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), tot_hotels, 584, 104);
  gtk_widget_set_size_request (tot_hotels, 17, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tot_hotels), 8226);

  enfants_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), enfants_hotels, 624, 40);
  gtk_widget_set_size_request (enfants_hotels, 17, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (enfants_hotels), 8226);

  bebes_hotels = gtk_entry_new ();
  gtk_fixed_put (GTK_FIXED (fixed19), bebes_hotels, 592, 32);
  gtk_widget_set_size_request (bebes_hotels, 17, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (bebes_hotels), 8226);

  g_signal_connect ((gpointer) treeview_payer_hotels, "row_activated",
                    G_CALLBACK (on_treeview_payer_hotels_row_activated),
                    NULL);
  g_signal_connect ((gpointer) modifier_payer_hotels, "clicked",
                    G_CALLBACK (on_modifier_payer_hotels_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer_payer_hotels, "clicked",
                    G_CALLBACK (on_supprimer_payer_hotels_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (historique_payer_hotels, historique_payer_hotels, "historique_payer_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, treeview_payer_hotels, "treeview_payer_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, modifier_payer_hotels, "modifier_payer_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, image14, "image14");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, label102, "label102");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, nom_hotels, "nom_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, supprimer_payer_hotels, "supprimer_payer_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, image15, "image15");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, label103, "label103");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, pays_hotels, "pays_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, nbe_hotels, "nbe_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, prix_hotels, "prix_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, adultes_hotels, "adultes_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, nbch_hotels, "nbch_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, tot_hotels, "tot_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, enfants_hotels, "enfants_hotels");
  GLADE_HOOKUP_OBJECT (historique_payer_hotels, bebes_hotels, "bebes_hotels");

  return historique_payer_hotels;
}

GtkWidget*
create_modifier_payer_hotels (void)
{
  GtkWidget *modifier_payer_hotels;
  GtkWidget *fixed20;
  GtkWidget *label115;
  GtkWidget *label116;
  GtkWidget *label117;
  GtkWidget *label118;
  GtkWidget *label119;
  GtkWidget *label120;
  GtkWidget *label121;
  GtkWidget *label122;
  GtkWidget *label123;
  GtkWidget *nom_modif;
  GtkWidget *pays_modif;
  GtkWidget *nbe_modif;
  GtkWidget *prix_modif;
  GtkWidget *nbch_modif;
  GtkWidget *adultes_modif;
  GtkWidget *enfants_modif;
  GtkWidget *bebs_modif;
  GtkWidget *tot_modif;
  GtkWidget *valider_modifier_payer_hotels;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label124;
  GtkWidget *label125;

  modifier_payer_hotels = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_payer_hotels), _("modifier"));

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (modifier_payer_hotels), fixed20);

  label115 = gtk_label_new (_("Nom d'hotel :"));
  gtk_widget_show (label115);
  gtk_fixed_put (GTK_FIXED (fixed20), label115, 30, 70);
  gtk_widget_set_size_request (label115, 112, 40);

  label116 = gtk_label_new (_("Pays :"));
  gtk_widget_show (label116);
  gtk_fixed_put (GTK_FIXED (fixed20), label116, 30, 130);
  gtk_widget_set_size_request (label116, 103, 40);

  label117 = gtk_label_new (_("Nombre d'etoiles :"));
  gtk_widget_show (label117);
  gtk_fixed_put (GTK_FIXED (fixed20), label117, 30, 180);
  gtk_widget_set_size_request (label117, 127, 40);

  label118 = gtk_label_new (_("Prix de la chambre"));
  gtk_widget_show (label118);
  gtk_fixed_put (GTK_FIXED (fixed20), label118, 16, 240);
  gtk_widget_set_size_request (label118, 128, 40);

  label119 = gtk_label_new (_("Nombre de chambre :"));
  gtk_widget_show (label119);
  gtk_fixed_put (GTK_FIXED (fixed20), label119, 16, 300);
  gtk_widget_set_size_request (label119, 150, 40);

  label120 = gtk_label_new (_("Adultes :"));
  gtk_widget_show (label120);
  gtk_fixed_put (GTK_FIXED (fixed20), label120, 24, 360);
  gtk_widget_set_size_request (label120, 104, 40);

  label121 = gtk_label_new (_("Enfants :"));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed20), label121, 40, 420);
  gtk_widget_set_size_request (label121, 72, 40);

  label122 = gtk_label_new (_("bebes :"));
  gtk_widget_show (label122);
  gtk_fixed_put (GTK_FIXED (fixed20), label122, 48, 480);
  gtk_widget_set_size_request (label122, 63, 40);

  label123 = gtk_label_new (_("Prix Total :"));
  gtk_widget_show (label123);
  gtk_fixed_put (GTK_FIXED (fixed20), label123, 32, 540);
  gtk_widget_set_size_request (label123, 114, 40);

  nom_modif = gtk_entry_new ();
  gtk_widget_show (nom_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), nom_modif, 170, 60);
  gtk_widget_set_size_request (nom_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom_modif), 8226);

  pays_modif = gtk_entry_new ();
  gtk_widget_show (pays_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), pays_modif, 168, 128);
  gtk_widget_set_size_request (pays_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (pays_modif), 8226);

  nbe_modif = gtk_entry_new ();
  gtk_widget_show (nbe_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), nbe_modif, 170, 180);
  gtk_widget_set_size_request (nbe_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbe_modif), 8226);

  prix_modif = gtk_entry_new ();
  gtk_widget_show (prix_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), prix_modif, 170, 240);
  gtk_widget_set_size_request (prix_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (prix_modif), 8226);

  nbch_modif = gtk_entry_new ();
  gtk_widget_show (nbch_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), nbch_modif, 168, 296);
  gtk_widget_set_size_request (nbch_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (nbch_modif), 8226);

  adultes_modif = gtk_entry_new ();
  gtk_widget_show (adultes_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), adultes_modif, 170, 360);
  gtk_widget_set_size_request (adultes_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (adultes_modif), 8226);

  enfants_modif = gtk_entry_new ();
  gtk_widget_show (enfants_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), enfants_modif, 170, 420);
  gtk_widget_set_size_request (enfants_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (enfants_modif), 8226);

  bebs_modif = gtk_entry_new ();
  gtk_widget_show (bebs_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), bebs_modif, 176, 480);
  gtk_widget_set_size_request (bebs_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (bebs_modif), 8226);

  tot_modif = gtk_entry_new ();
  gtk_widget_show (tot_modif);
  gtk_fixed_put (GTK_FIXED (fixed20), tot_modif, 170, 540);
  gtk_widget_set_size_request (tot_modif, 200, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (tot_modif), 8226);

  valider_modifier_payer_hotels = gtk_button_new ();
  gtk_widget_show (valider_modifier_payer_hotels);
  gtk_fixed_put (GTK_FIXED (fixed20), valider_modifier_payer_hotels, 288, 600);
  gtk_widget_set_size_request (valider_modifier_payer_hotels, 83, 40);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (valider_modifier_payer_hotels), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label124 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label124);
  gtk_box_pack_start (GTK_BOX (hbox17), label124, FALSE, FALSE, 0);

  label125 = gtk_label_new (_("<b><i><span foreground=\"darkcyan\" size=\"xx-large\">Sky Travel</span></i></b>"));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed20), label125, 24, 8);
  gtk_widget_set_size_request (label125, 171, 42);
  gtk_label_set_use_markup (GTK_LABEL (label125), TRUE);

  g_signal_connect ((gpointer) valider_modifier_payer_hotels, "clicked",
                    G_CALLBACK (on_valider_modifier_payer_hotels_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_payer_hotels, modifier_payer_hotels, "modifier_payer_hotels");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label115, "label115");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label116, "label116");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label117, "label117");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label118, "label118");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label119, "label119");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label120, "label120");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label121, "label121");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label122, "label122");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label123, "label123");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, nom_modif, "nom_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, pays_modif, "pays_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, nbe_modif, "nbe_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, prix_modif, "prix_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, nbch_modif, "nbch_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, adultes_modif, "adultes_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, enfants_modif, "enfants_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, bebs_modif, "bebs_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, tot_modif, "tot_modif");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, valider_modifier_payer_hotels, "valider_modifier_payer_hotels");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, image17, "image17");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label124, "label124");
  GLADE_HOOKUP_OBJECT (modifier_payer_hotels, label125, "label125");

  return modifier_payer_hotels;
}

