/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_client (void);
GtkWidget* create_payer_hotels (void);
GtkWidget* create_Login (void);
GtkWidget* create_payer_vols (void);
GtkWidget* create_payer_sejours (void);
GtkWidget* create_payer_location_voitures (void);
GtkWidget* create_profile (void);
GtkWidget* create_Modification_des_informations (void);
GtkWidget* create_window_ajouter_recmlamation (void);
GtkWidget* create_modifier_reclamation_client (void);
GtkWidget* create_window2 (void);
GtkWidget* create_historique_payer_hotels (void);
GtkWidget* create_modifier_payer_hotels (void);
